import { describe, expect, it, vi } from "vitest";

import pairingContractJson from "../../src-tauri/test-fixtures/mobile-pairing-contract.json?raw";

import {
  createNativePairingScanner,
  isNativeMobileRuntime,
  MobilePairingCodeError,
  parseNoteSpacePairingPayload,
  type PairingScannerNativeAdapter,
} from "./pairingScanner";

const PAIRING_CONTRACT = JSON.parse(pairingContractJson) as {
  readonly version: number;
  readonly instanceId: string;
  readonly host: string;
  readonly port: number;
  readonly nonce: string;
  readonly fingerprint: string;
  readonly payload: string;
};
const INSTANCE_ID = PAIRING_CONTRACT.instanceId;
const NONCE = PAIRING_CONTRACT.nonce;
const FINGERPRINT = PAIRING_CONTRACT.fingerprint
  .toUpperCase()
  .replace("SHA256:", "sha256:");

function payload(overrides: Record<string, readonly string[] | string> = {}) {
  const values: Record<string, readonly string[]> = {
    v: ["1"],
    instance: [INSTANCE_ID],
    host: ["192.168.1.20"],
    port: ["43127"],
    nonce: [NONCE],
    fingerprint: [FINGERPRINT],
  };
  for (const [key, value] of Object.entries(overrides)) {
    values[key] = typeof value === "string" ? [value] : value;
  }
  const parameters = new URLSearchParams();
  for (const [key, items] of Object.entries(values)) {
    for (const item of items) parameters.append(key, item);
  }
  return `notespace://pair?${parameters}`;
}

function adapter(
  overrides: Partial<PairingScannerNativeAdapter> = {},
): PairingScannerNativeAdapter {
  return {
    checkCameraPermission: vi.fn(async () => "granted" as const),
    requestCameraPermission: vi.fn(async () => "granted" as const),
    scanQrCode: vi.fn(async () => ({ content: payload(), format: "QR_CODE" })),
    ...overrides,
  };
}

describe("parseNoteSpacePairingPayload", () => {
  it("accepts the pairing contract generated by the Rust core", () => {
    expect(parseNoteSpacePairingPayload(PAIRING_CONTRACT.payload)).toMatchObject({
      address: `${PAIRING_CONTRACT.host}:${PAIRING_CONTRACT.port}`,
      pairingCode: PAIRING_CONTRACT.nonce,
      certificateFingerprint: PAIRING_CONTRACT.fingerprint,
      instanceId: PAIRING_CONTRACT.instanceId,
      protocolVersion: PAIRING_CONTRACT.version,
    });
  });

  it("parses and normalizes a bounded NoteSpace payload with address candidates", () => {
    expect(
      parseNoteSpacePairingPayload(
        payload({ host: ["DESKTOP.local", "192.168.1.20", "fd00::8"] }),
      ),
    ).toEqual({
      address: "desktop.local:43127",
      addressCandidates: ["desktop.local:43127", "192.168.1.20:43127", "[fd00::8]:43127"],
      pairingCode: NONCE,
      certificateFingerprint: PAIRING_CONTRACT.fingerprint,
      instanceId: INSTANCE_ID,
      protocolVersion: 1,
    });
  });

  it.each([
    ["wrong scheme", payload().replace("notespace:", "https:")],
    ["unknown field", `${payload()}&token=secret`],
    ["duplicate singleton", `${payload()}&v=1`],
    ["unsupported version", payload({ v: "2" })],
    ["invalid instance", payload({ instance: "short" })],
    ["loopback address", payload({ host: "127.0.0.1" })],
    ["public address", payload({ host: "203.0.113.8" })],
    ["public hostname", payload({ host: "example.com" })],
    ["invalid port", payload({ port: "65536" })],
    ["invalid nonce", payload({ nonce: "PAIR-1234" })],
    ["invalid fingerprint", payload({ fingerprint: "sha256:not-a-pin" })],
    ["duplicate address", payload({ host: ["desktop.local", "desktop.local"] })],
    ["too many addresses", payload({ host: ["one", "two", "three", "four", "five"] })],
    ["surrounding whitespace", ` ${payload()}`],
    ["non-ASCII data", `${payload()}中文`],
    ["oversized data", `notespace://pair?${"a".repeat(4_100)}`],
  ])("rejects %s without exposing payload data", (_name, input) => {
    expect(() => parseNoteSpacePairingPayload(input)).toThrow(MobilePairingCodeError);
    try {
      parseNoteSpacePairingPayload(input);
    } catch (error) {
      expect(String(error)).not.toContain(NONCE);
    }
  });
});

describe("createNativePairingScanner", () => {
  it("requests a prompt camera permission and scans only QR codes", async () => {
    const native = adapter({
      checkCameraPermission: vi.fn(async () => "prompt" as const),
      requestCameraPermission: vi.fn(async () => "granted" as const),
    });
    const scan = createNativePairingScanner({
      loadAdapter: vi.fn(async () => native),
    });

    await expect(scan()).resolves.toMatchObject({
      address: "192.168.1.20:43127",
      pairingCode: NONCE,
    });
    expect(native.requestCameraPermission).toHaveBeenCalledOnce();
    expect(native.scanQrCode).toHaveBeenCalledOnce();
  });

  it("does not open the scanner when camera permission is denied", async () => {
    const native = adapter({
      checkCameraPermission: vi.fn(async () => "denied" as const),
    });
    const scan = createNativePairingScanner({
      loadAdapter: async () => native,
    });

    await expect(scan()).rejects.toThrow("相机权限");
    expect(native.requestCameraPermission).not.toHaveBeenCalled();
    expect(native.scanQrCode).not.toHaveBeenCalled();
  });

  it("shows a safe explanation for malformed QR data", async () => {
    const scan = createNativePairingScanner({
      loadAdapter: async () =>
        adapter({
          scanQrCode: vi.fn(async () => ({
            content: `https://example.test/?nonce=${NONCE}`,
            format: "QR_CODE",
          })),
        }),
    });

    await expect(scan()).rejects.toThrow("NoteSpace 配对二维码");
    await scan().catch((error: unknown) => expect(String(error)).not.toContain(NONCE));
  });

  it("treats closing the native scanner as cancellation", async () => {
    const scan = createNativePairingScanner({
      loadAdapter: async () =>
        adapter({ scanQrCode: vi.fn(async () => Promise.reject(new Error("cancelled"))) }),
    });

    await expect(scan()).resolves.toBeNull();
  });

  it("does not enable the native scanner for a browser or desktop surface", () => {
    expect(isNativeMobileRuntime("mobile", false)).toBe(false);
    expect(isNativeMobileRuntime("desktop", true)).toBe(false);
    expect(isNativeMobileRuntime("mobile", true)).toBe(true);
  });
});
